import Image from 'next/image';
import Link from 'next/link';

export const fetchArtists = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function Artists() {
  const url: string =
    'https://spotify23.p.rapidapi.com/artists/?ids=3dfQn1ijJNptfREJB2rRd2';

  interface IAPIOptions {
    method: string;
    headers: {
      'X-RapidAPI-Key': string;
      'X-RapidAPI-Host': string;
    };
  }

  if (!process.env.RAPID_API_KEY) {
    return;
  }

  const options: IAPIOptions = {
    method: 'GET',
    headers: {
      'X-RapidAPI-Key': process.env.RAPID_API_KEY,
      'X-RapidAPI-Host': 'spotify23.p.rapidapi.com',
    },
  };

  const response = await fetch(url, options);
  const artists = await response.json();
  console.log(artists);

  return (
    <main>
      <h1>Welcome to my soon-to-be-not-so-blank page, y'all! ;3</h1>
      {/* {JSON.stringify(artists)}
      {artists.images.map((artist) => {
        const artist = artists.images[0];
        return (
          <div key={`artist-div-${artist.id}`}>
            <Image
              alt="AI cover art albums"
              width={300}
              height={300}
              src={images}
            />
            <div>Artist: {artist.name}</div>
          </div>
        );
      })} */}
    </main>
  );
}
