import Image from 'next/image';
import Link from 'next/link';

export const fetchAlbums = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function Albums() {
  const url: string =
    'https://spotify23.p.rapidapi.com/artist_albums/?id=3dfQn1ijJNptfREJB2rRd2';

  interface IAPIOptions {
    method: string;
    headers: {
      'X-RapidAPI-Key': string;
      'X-RapidAPI-Host': string;
    };
  }

  if (!process.env.RAPID_API_KEY) {
    return;
  }

  const options: IAPIOptions = {
    method: 'GET',
    headers: {
      'X-RapidAPI-Key': process.env.RAPID_API_KEY,
      'X-RapidAPI-Host': 'spotify23.p.rapidapi.com',
    },
  };

  const response = await fetch(url, options);
  const albums = await response.json();
  console.log('result', albums.data.artist.discography.albums.items[0]);

  return (
    <main>
      <h1>Welcome to my soon-to-be-not-so-blank page, y'all! ;3</h1>

      {JSON.stringify(albums)}
      {albums.data.artist.discography.albums.items.map((album) => {
        const release = album.releases.items[0];
        console.log(
          'release map',
          album.releases.items[0].coverArt.sources[2].url,
        );
        return (
          <div key={`album-div-${release.id}`}>
            <iframe
              title="unique"
              sandbox="allow-popups"
              src={`https://open.spotify.com/embed/album/${release.id}?utm_source=generator`}
              width="100%"
              height="352"
              frameBorder="0"
              allowfullscreen=""
              allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"
              loading="lazy"
            />
            <Image
              src={album.releases.items[0].coverArt.sources[2].url}
              alt="cover art albums"
              width={300}
              height={300}
            />
            <div>Album name: {release.name}</div>
            <div>Release year: {release.date.year}</div>
          </div>
        );
      })}
    </main>
  );
}
