export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function Music() {
  const url = 'https://api.deezer.com/artist/126876/top?limit=35';
  const options = {
    method: 'GET',
    headers: {
      'X-RapidAPI-Key': process.env.RAPID_API_KEY,
      'X-RapidAPI-Host': 'deezerdevs-deezer.p.rapidapi.com',
    },
  };

  try {
    const response = await fetch(url, options);
    const data = await response.json();
    console.log(data);
  } catch (error) {
    console.error(error);
  }

  return (
    <main>
      <h1>Welcome to my soon-to-be-not-so-blank page, y'all! ;3</h1>
    </main>
  );
}
